spring:
  rabbitmq:
    host: 192.168.1.159
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true  #  消息发送到交换机确认机制,是否返回回馈
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
        default-requeue-rejected: false 
        acknowledge-mode: manual

  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'

  jpa:
      hibernate:
        ddl-auto: update  #update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


hdfs:
  path: hdfs://localhost:9000
  username: Administrator
  replication: 1
  buffersize: 1048576
  blocksize: 104857600
  overwrite: true

feign:
  hystrix:
    enabled: true

###配置请求超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 4000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 1000
  MaxAutoRetries: 1 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
