zuul:
  routes:
    api-transfer:
      path: /api-transfer/**
      serviceId: service-transfer
    api-ftp:
      path: /api-ftp/**
      serviceId: service-ftp
    api-hdfs:
      path: /api-hdfs/**
      serviceId: service-hdfs
    api-hdfs-upload:
      path: /api-hdfs-upload/**
      url: http://localhost:8766/

  host:
     max-per-route-connections: 10000
     socket-timeout-millis: 10000
     connect-timeout-millis: 10000

ribbon:
  ReadTimeout: 10000
  SocketTimeout: 10000
